"""Add professor_id to attendance sheet

Revision ID: 0d7557ee74a7
Revises: 
Create Date: 2025-05-13 17:23:29.308717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d7557ee74a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'professor', ['professor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professor_id')

    op.create_table('sectionaccessrequest',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('professor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], name='sectionaccessrequest_ibfk_1'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name='sectionaccessrequest_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
